# File: .github/workflows/deploy.yml
name: CI/CD Pipeline

# ---------- EVENT TRIGGERS ----------
on:
  # Re‑deploy any time you push to `master`
  push:
    branches: [master]

  # Allow manual runs from the Actions tab
  workflow_dispatch:

# ---------- DEFAULT PERMISSIONS ----------
permissions:
  contents: read        # to checkout the repo
  pages: write          # to publish to Pages
  id-token: write       # to authenticate to Pages

# ---------- JOBS ----------
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Enable Pages for this repo (only needed the first time)
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      # 2. Check out source
      - uses: actions/checkout@v4

      # 3. Setup pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.x

      # 4. Run linting, formatting and type checking
      - name: Run checks
        run: |
          pnpm install
          pnpm approve-builds
          pnpm format || true
          pnpm lint || true
          pnpm check || true

      # 5. Build and upload artifacts
      - name: Build with Astro
        uses: withastro/action@v4
        with:
          node-version: 22
          package-manager: pnpm@latest

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      # 6. Deploy the artifact produced by the build job
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4